### PR TITLE
reducing toolchain files to a single one

### PR DESCRIPTION
**Pull request by TornaxO7**
follow up of https://github.com/arijit79/minus/pull/112

### CODE REVIEW

**Comment by TornaxO7** [comment]
Yeah! Now CI is passing :)

**Comment by arijit79** [comment]
Fine! Let's just keep it this way.

**Comment by arijit79** [comment]
I pulled the latest main today and I noticed that now rust_analyzer is not working for me. I use the official rust_analyzer package and not the rust_analyzer provided by the rust toolchains because I often find them outdated.

I investigated more and found out that in my Neovim setup and it requires me to install rust_analyzer from the rust toolchains and then it works with toolchain rust_analyzer. Since I have my `.local/bin` prioritized over `.cargo/bin`, it can also use my downloaded version of rust_analyzer. So in all effect, you need to have rust_analyzer installed from the rust toolchain to run any version of rust_analyzer. I also noticed that even if you remove rust_analyzer from the toolchain, it automatically reinstalls it,

**Comment by TornaxO7** [comment]
hm... ok, let me try something out. I'll create a PR

**Pull request merged**
