### PR TITLE
nix: moving `flake.nix` and `flake.lock` back to root

### PR DESCRIPTION
**Pull request by TornaxO7**
Looks like that it doesn't work (somehow it used to work on my pc?):
```
path '/home/tornax/Programming/minus' does not contain a 'flake.nix', searching up
error: path '/home/tornax/Programming/minus' is not part of a flake (neither it nor its parent directories contain a 'flake.nix' file)
direnv: export ~PATH
```

### CODE REVIEW

**Comment by arijit79** [comment]
Hmmm...What command are you running exactly?

**Comment by TornaxO7** [comment]
> Hmmm...What command are you running exactly?

Either none (since it gets automatically loaded) or `nix develop`.

**Comment by TornaxO7** [comment]
It's really common that `flake.nix` and `flake.lock` exist in the root directory.

**Comment by arijit79** [comment]
> Either none (since it gets automatically loaded)

Its because you left the `.envrc` file in the root dir. Put it in the `nix` dir and `cd` into it. I think that should do the trick.

> or `nix develop`.

Just call `nix develop` in the `nix` dir. IIRC there's also a `-f` flag to set the path to `flake.nix` file.

> It's really common that flake.nix and flake.lock exist in the root directory.

I have seen many projects putting all the nix stuff in a single `nix` dir.

**Comment by TornaxO7** [comment]
> I have seen many projects putting all the nix stuff in a single nix dir :).

Huh, all? I'm aware of packaging and modules but I'm definetely sure that everyone puts at least `flake.lock` and `flake.nix` in the root directory.

> Its because you left the .envrc file in the root dir. Put it in the nix dir and cd into it, I think that should do the trick.

That doesn't work because it unloads if I leave the `nix` directory.

> Just call nix develop in the nix dir. IIRC there's also a -f flag to set the path to flake.nix file.

Not that I'm aware of and `-f` doesn't seem to exist for `nix develop`.

**Comment by arijit79** [comment]
Fine I am just merging this.

**Pull request merged**
