### PR TITLE
adding "rust-src" to devShell

### PR DESCRIPTION
**Pull request by TornaxO7**
`rust-analyzer` doesn't work for me, because I also need `rust-src` but flakes `override` wipes the entries in the toolchain.

### CODE REVIEW

**Comment by TornaxO7** [comment]
> I think the best option then would be to just drop the rust-toolchain.toml and configure the devShell in flake.nix only.

so you would say that you don't want the rust-toolchain.toml at all?

**Comment by arijit79** [comment]
I think that's enough clear in the README about the MSRV plus there's no such problem with the nightly release (I can say that because I run the latest nightly) and all the intermediate releases. Hence I don't know how useful is that file for non-nix user. I mean I atleast have to run `cargo` with `+nightly` flag always. Rest I can only respect other people's DXs on this stuff.

**Comment by TornaxO7** [comment]
Okeydokey!

**Comment by TornaxO7** [comment]
done!

**Comment by arijit79** [comment]
Merged.

**Pull request merged**
