### PR TITLE
Refactor some parts to improve docs/perfs/clarity

### PR DESCRIPTION
**Pull request by poliorcetics**

### CODE REVIEW

**Comment by arijit79** [comment]
Thanks for the PR and all the hard work you have done. I am really thankful to you. I think this is probably going to be the last PR before I release 2.0.0.

**Comment by poliorcetics** [comment]
You're very welcome, a Rust-only paging library that also works on Windows is a very nice thing !

I'm not done just yet with this PR but I'm moving as fast as possible while trying to design for testability. 😄

**Comment by arijit79** [comment]
Yeash! You are free to take time. Really appreciate your contribution

**Comment by poliorcetics** [comment]
This is finally done ! I added **lots** of tests, which necessitated a lot of refactoring here and there.

I also factored out several functions to remove a lot of duplications.

I used the `Error` type and `Result` alias extensively in the process to (hopefully) gracefully handle as much errors as possible.

Finally I reworked the way events and drawing are done to avoid having to interleave event handling and drawing.

This PR is a ~1300 lines change so you should probably download it locally, the Github interface will probably be a hindrance here.

Don't hesitate to criticise my choices and to make remarks, this is your crate after all !

**Comment by arijit79** [comment]
This is really impressive work. I am very thankful to you. There are some minor things that I want to change. Merging this now. Thanks again

**Pull request merged**
