### PR TITLE
replace PagerMutex implementation with type alias to async_std::sync:Mutex

### LINKED ISSUE #26: async runtime segfaults when working with large strings
Please refer to the segfault example in this branch:

```
https://github.com/rezural/minus/tree/segfault
```

run with:

```
cargo run --example segfault --features=async_std_lib

```
if you uncomment the line with prints the bytes_written, you can see that it segfaults semi randomly. sometimes at 50000 bytes_written, sometimes at 4 million.

I am actually hitting these segfaults when paging the output of ls **/* (or find) in a folder with a large number of files.

### PR DESCRIPTION
**Pull request by rezural**
This uses async_std::sync::Mutex, as the homegrown implementation was causing segfaults with large amounts of data.

Fixes #26 .

### CODE REVIEW

**Comment by rezural** [comment]
This actually uses async_std::sync::Mutex by default, and tokio::sync::Mutex if async_std is not available.

There is some funky cfg stuff around importing Mutex depending on if we are async_std, tokio, or both.

This is mainly to get the tests working. which run with --all-features.

It may make more sense to run tests on CI with 
```
--features=async_std ...
AND
--features=tokio ...
```
separately

I'm not sure if this is desired behaviour, or just cruft.. your input welcome.

Thanks

**Comment by arijit79** [comment]
Thanks for your kind effort. I think we should raise a compile error if someone uses both the `tokio_lib` feature and `async_std_lib` feature

**Comment by rezural** [comment]
Shall I add it to this PR?

It will require changing the tests where applicable, and also the ci.yml, to run tests as tokio only, and async_std only.

Thankyou

**Comment by rezural** [comment]
I have gone ahead and made fixes that make sense.

SO: 
- This also cleans up the rt_wrapper code (putting each runtime function in a separate module)
- so they can be included separately, and the doc examples build without erroring out.

**Comment by rezural** [comment]
And,

I have had to change the ci.yml, to run only each separate run-time individually.

**Pull request merged**
