### PR TITLE
doc: adding keybinding entry for toggling follow-mode

### PR DESCRIPTION
**Pull request by TornaxO7**
I forgot this in https://github.com/arijit79/minus/pull/114 :D

### CODE REVIEW

**Comment by arijit79** [comment]
You should also them in the README as well.

**Comment by TornaxO7** [comment]
> You should also them in the README as well.

Hm... I've got an idea: Why add a link to the README which brings them to the [doc section](https://docs.rs/minus/latest/minus/index.html#standard-actions) for key bindings so that you don't have to maintain both tables?

**Comment by arijit79** [comment]
Yeah! That could be done as well. I will merge this and then we can refactor the README in a separate PR.

**Comment by arijit79** [comment]
That's so great of you. Now, you don't have to go through everything in one go or in a day as I too don't get much time to work on minus. Hence we will take each module one by one every few days and improve it by making separate PRs. It would be beneficial if you have joined either discord/matrix so that it is easier to chat on stuff.

**Comment by TornaxO7** [comment]
`tornaxo7` here's my discord user name :)

**Pull request merged**
