### PR TITLE
improving doc for `lib.rs`

### PR DESCRIPTION
**Pull request by TornaxO7**
continues https://github.com/arijit79/minus/pull/122

### CODE REVIEW

**Comment by arijit79** [comment]
I think we should include a common patterns section or something like that to give a brief example of some of the major features of minus and then direct them to the respective modules which concerns that stuff.

**Comment by TornaxO7** [comment]
I'm unsure about that because this might become complicated.
When I started to use your library, your example section was helping me a lot and I then just used the search bar to get more information about the structs. In my opinion that was fine and also good.

**Comment by arijit79** [comment]
Well then let's drop this idea.

**Comment by TornaxO7** [comment]
> Well then let's drop this idea.

Nono, you can create a suggestion-structure if you want. That's just _my opinion_! It doesn't mean that I'm right :)

**Comment by arijit79** [comment]
Nah I will add them in the individual modules so that's it's easier for the reader to understand the stuff. If later down the line I feel that we need something like this, I will just add it then.

**Comment by arijit79** [comment]
Merged.

**Pull request merged**
