### PR TITLE
Add ability to only engage the paging behaviour, if we have overflowed the screen rows

### PR DESCRIPTION
**Pull request by rezural**
As above,

This would be nice, for inclusion into the nushell ecosystem. Otherwise the paging makes the usability feel awkward (always paging). I tried doing this on nushell side, but this makes it alot easier & I was not able to get it working in the end the other way with async et al.

This still clears the screen each draw, but doesnt output all the other stuff, unless we have overflowed.

It may make more sense to have completely separate setup & cleanup sequences for each modes and:

if we over flow & page_if_havent_overflowed  == false, rerun setup which will clear the screen etc.
run different cleanup routines if we have overflowed, or not.

This also adds a data_finished() method, which flags to the system that data is no longer coming. This only makes sense when page_if_havent_overflowed == false. if we have finished data, and havent overflowed, we return out of the run loop.

There may be issues with static pager, I havent tested it yet. but it would also be good to have some tests for these functions, that test what the actual output to the screen is, if possible. might be fairly impossible with terminal emulatioin etc.

Hope this makes sense!

### CODE REVIEW

**Comment by arijit79** [comment]
The problem with the approach is that we cannot say that at least in async mode whether the end application has written all data. I have implemented this in the static mode but I am not sure whether adding this in async would be any good

**Comment by rezural** [comment]
Hey,

I think that last commit broke something. apologies, I will fix this.

Cheers

**Comment by rezural** [comment]
I squashed this down, to minimize churn.

Again, apologies. I left the house while the the CI was running, and didnt come back for a few hours & forgot to check.

Thankyou

**Comment by arijit79** [comment]
Since all tests are working fine and there's only a rustfmt job failing. I am going to merge this

**Comment by rezural** [comment]
Ah, whoops.

I'll put up a new pr (it's one newline dang it)

**Pull request merged**
