### PR TITLE
Fix bug where moving to the last search term, locks onto that search, and the user cannot go to the previous search match.

### PR DESCRIPTION
**Pull request by rezural**
This removes the if clauses, and just clamps the value of s_mark to 0..s_co.len() - 1

### CODE REVIEW

**Comment by arijit79** [comment]
Thanks. I really appreciate that. Merging the PR

**Comment by rezural** [comment]
To reproduce this bug:

search for anything that has more than one frequency, navigate to the last search (n?), then try to navigate to the previous search, you will find that it is locked to the last match.

Thanks

**Comment by Type1J** [comment]
This PR seems to cause:
```
error[E0658]: use of unstable library feature 'clamp'
   --> C:\Users\jaysi\.cargo\registry\src\github.com-1ecc6299db9ec823\minus-3.3.1\src\init.rs:267:37
    |
267 |                     s_mark = s_mark.clamp(0, s_co.len() as isize - 1);
    |                                     ^^^^^
    |
    = note: see issue #44095 <https://github.com/rust-lang/rust/issues/44095> for more information
 ```

**Comment by Type1J** [comment]
Nevermind. A `rustup update` fixed it.

**Pull request merged**
