### PR TITLE
Feat: Add following mode

### PR DESCRIPTION
**Pull request by TornaxO7**
Closes https://github.com/arijit79/minus/issues/113
Closes https://github.com/arijit79/minus/issues/81

I haven't added any docs yet because I'm unsure how I can test it and I'd like to get some suggestions from you first, like if it's fine how I changed the code :)

### CODE REVIEW

**Comment by arijit79** [comment]
The implementation seems to be ok however there are still a few things left:-
- The `f` keybinding just doesn't work.
- I think this feature shouldn't be the on by default. Most people want text to scroll down at their own will. It's the only reason why people use a pager. However we should give end-applications freedom to control this behavior which I see you have done.
- Can we have a better key binding like `C-f` rather than just `f`.

**Comment by TornaxO7** [comment]
@arijit79 update :D

**Comment by arijit79** [comment]
You missed my point actually. I was saying that in static output, the pager should jump to the last line only if follow mode is enabled so that it matches with the functionality of dynamic mode. Also your code fails to compile. Also the ToggleSearch keybinding still does not work: its likely you didn't add it in the newer input system.  I am making a commit to fix these issues.

**Comment by arijit79** [comment]
Thanks for 9e9b273. I didn't even notice that.

**Comment by TornaxO7** [comment]
> EDIT: BTW I am working on the issue that I talked in my earlier comment. I will post it later today.

oh eh, I already pushed a change, which, if I understood you correctly, should address the issue. :sweat_smile:

**Comment by arijit79** [comment]
No that wasn't exactly what I was talking about. I had already pushed a commit fixing exactly the same issue that you pushed. Don't worry I will fix the issue today.

**Comment by TornaxO7** [comment]
> No that wasn't exactly what I was talking about. I had already pushed a commit fixing exactly the same issue that you pushed. Don't worry I will fix the issue today.

oh, sorry... so should I let you do the changes for the time being?

**Comment by arijit79** [comment]
I have pushed the changes. You can try them to report any errors/bugs that you find.

**Comment by TornaxO7** [comment]
> I have pushed the changes. You can try them to report any errors/bugs that you find.

May I ask how I can test it out? Do I have to implement a custom binary which uses the lib?

**Comment by arijit79** [comment]
You can try it out in any of the examples.

**Comment by TornaxO7** [comment]
I've got an idea: Would be neat, if the statusbar could show an indicator that it's currently in "following-mode".

**Comment by arijit79** [comment]
I was thinking about the same while writing the code and I have planned for it. We could use a traditional solution right now But it would get much easier to implement once I introduce**command queue** feature which would allow us to chain another command after the current command is executed.
This would take me a day to get there.

Other then that I think this PR is ready so if you want this immediately on the main branch, I can merge this otherwise I will keep this until I get the status bar message thing going.

**Comment by TornaxO7** [comment]
whoops.... I read your message too late ;-;
I can revert the changes if you want.

**Comment by TornaxO7** [comment]
> I was thinking about the same while writing the code and I have planned for it. We could use a traditional solution right now But it would get much easier to implement once I introduce**command queue** feature which would allow us to chain another command after the current command is executed. This would take me a day to get there.

Sounds good!

> Other then that I think this PR is ready so if you want this immediately on the main branch, I can merge this otherwise I will keep this until I get the status bar message thing going.

I don't need it now, so you can implement the command queue first

**Comment by arijit79** [comment]
It's good but I was thinking about using a message rather than adding an entire block to show that. If static text is required we could also use a single character for that. What do you say?

**Comment by TornaxO7** [comment]
> It's good but I was thinking about using a message rather than adding an entire block to show that.

hm... may I ask what you mean with "message"?

>  If static text is required we could also use a single character for that. What do you say?

On the one hand I'd prefer to have this static text because it's self-explaining what it indicates. If there will be more entries, a single letter would be fine but on the other hand a `[F]` might be already self-explaining I think

**Comment by arijit79** [comment]
A message in minus allows you to show a text message to the user at the prompt site. It would disappear when the user presses any other key/does a mouse action. We can display a message like `Follow output enabled` when it is enabled. If you want to know more about a message, try `msg-tokio` example to see a practical demo of it.

**Comment by TornaxO7** [comment]
> A message in minus allows you to show a text message to the user at the prompt site. It would disappear when the user presses any other key/does a mouse action. We can display a message like `Follow output enabled` when it is enabled. If you want to know more about a message, try `msg-tokio` example to see a practical demo of it.

oh ok. So, I'd prefer a static text because assuming you're looking through some logs and you forgot that you enabled follow mode, you'll start scrolling up but after some time something new appears and you'll be thrown back to the bottom because you forgot that you are in the follow-mode.

**Comment by arijit79** [comment]
Hmm. Fine then.

**Comment by TornaxO7** [comment]
but yeah, now I'm quite happy with the result :+1:

**Comment by arijit79** [comment]
Let's merge this then. I will introduce minor improvements on this in future commits.

**Pull request merged**
