### PR TITLE
Investigate screen flickering on WSL/Windows Terminal

### PR DESCRIPTION
**Pull request by arijit79**
@EiEddie can you test your code from this branch?. It will print out the events on the screen before handling them on the screen. This will help us investigate all the events that the event reader is reading.

### CODE REVIEW

**Comment by EiEddie** [comment]
I test using the new code, and find it always print 
```
[src/core/init.rs:329] inp = Ignore
```
when I moving my mouse.

Further, I found that everything I do that can make program to get an `Ignore` event, like press a useless key, would cause the screen to flicker. Flickering when mouse moving is because moving of mouse produce tons of `Ignore` event, and make program incessant flashing.

**Comment by arijit79** [comment]
Can you check if the latest commit fixed the problem?

**Comment by EiEddie** [comment]
Yes!
Perfect, it does not flicker anymore.

**Comment by arijit79** [comment]
The solution I pushed now is hacky. It will get cleaned up when I merge #119. Anyways I am merging this.

**Comment by arijit79** [comment]
Merged. Thanks @EiEddie for all your help.

**Comment by arijit79** [comment]
@EiEddie I have pushed a patch release containing these changes. You can get it from crates.io.

**Pull request merged**
